trigger:
  branches:
    include:
      - main  # Ou 'QA' se você preferir que a build seja disparada a partir de outra branch

pool:
  vmImage: 'windows-latest'  # Usando uma máquina virtual do Azure DevOps com Windows

variables:
  buildConfiguration: 'Release'

steps:
# Usar a versão do .NET necessária
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # Versão do .NET que você deseja instalar
    installationPath: $(Agent.ToolsDirectory)/dotnet
  displayName: 'Install .NET SDK'

# Restaurar pacotes NuGet
- script: |
    echo Restoring NuGet packages
    dotnet restore backoffice/Flytec.sln
  displayName: 'Restore NuGet Packages'

# Construir o projeto
- script: |
    echo Building project
    dotnet build backoffice/Flytec.sln --configuration $(buildConfiguration)
  displayName: 'Build Project'

# Publicar artefatos gerados
- script: |
    echo Publishing artifacts
    dotnet publish backoffice/Flytec.sln --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Artifacts'

# Publicar os artefatos para o Azure DevOps
- publish: $(Build.ArtifactStagingDirectory)
  artifact: drop
  displayName: 'Publish Build Artifacts'
