trigger:
  branches:
    include:
      - QA  # Ou 'QA' se você preferir que a build seja disparada a partir de outra branch

pool:
  vmImage: 'windows-latest'  # Usando uma máquina virtual do Azure DevOps com Windows

variables:
  buildConfiguration: 'Release'

steps:
# Usar a versão do .NET necessária
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # Versão do .NET que você deseja instalar
    installationPath: $(Agent.ToolsDirectory)/dotnet
  displayName: 'Install .NET SDK'

# Restaurar pacotes NuGet
- script: |
    echo Restoring NuGet packages
    dotnet restore backoffice/Flytec.sln
  displayName: 'Restore NuGet Packages'

# Listar os arquivos no diretório atual para verificar o caminho
- script: |
    echo "Listando arquivos no diretório atual:"
    ls -R
  displayName: 'Diagnóstico de Arquivos'

# Construir o projeto principal
- script: |
    echo Building project
    dotnet build backoffice/WebApi/WebApi.csproj --configuration $(buildConfiguration)
  displayName: 'Build Project'

# Publicar artefatos gerados
- script: |
    echo Publishing artifacts
    dotnet publish backoffice/WebApi/WebApi.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Artifacts'

# Publicar os artefatos para o Azure DevOps
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' # Diretório onde os artefatos foram gerados
    artifact: drop
    publishLocation: 'pipeline' # Publicar no pipeline
  displayName: 'Publish Build Artifacts'
