// <auto-generated />
using System;
using Infra.Configuracao;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(ContextBase))]
    partial class ContextBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entidades.Cadastros.Adjuvante.Adjuvante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Adjuvante");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aeronave.Aeronave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fabricante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prefixo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aeronave");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Altura_Voo.AlturaVoo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AlturaVoo");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Alvo_Biologico.AlvoBiologico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DoseProdutoPorHectare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdProduto")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdProduto");

                    b.ToTable("AlvoBiologico");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aplicacao.Aplicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("IdCultura")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdExecutor")
                        .HasColumnType("int");

                    b.Property<int?>("IdPiloto")
                        .HasColumnType("int");

                    b.Property<string>("StatusEnvio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdCultura");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdExecutor");

                    b.HasIndex("IdPiloto");

                    b.ToTable("Aplicacao");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aplicacao.AplicacaoAreaTratada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Extensao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("IdAplicacao")
                        .HasColumnType("int");

                    b.Property<int?>("IdCidade")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdAplicacao");

                    b.HasIndex("IdCidade");

                    b.HasIndex("IdEstado");

                    b.ToTable("AplicacaoAreaTratada");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aplicacao.AplicacaoCaracteristicas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdAdjuvante")
                        .HasColumnType("int");

                    b.Property<int?>("IdAplicacao")
                        .HasColumnType("int");

                    b.Property<int?>("IdProduto")
                        .HasColumnType("int");

                    b.Property<string>("TipoDeServico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdAdjuvante");

                    b.HasIndex("IdAplicacao");

                    b.HasIndex("IdProduto");

                    b.ToTable("AplicacaoCaracteristicas");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aplicacao.AplicacaoContrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assinatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPFCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdAplicacao")
                        .HasColumnType("int");

                    b.Property<int?>("IdCidade")
                        .HasColumnType("int");

                    b.Property<int?>("IdUF")
                        .HasColumnType("int");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdAplicacao");

                    b.HasIndex("IdCidade");

                    b.HasIndex("IdUF");

                    b.ToTable("AplicacaoContrato");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aplicacao.AplicacaoCroqui", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desenho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdAplicacao")
                        .HasColumnType("int");

                    b.Property<int?>("IdMapa")
                        .HasColumnType("int");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdAplicacao");

                    b.ToTable("AplicacaoCroqui");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aplicacao.AplicacaoCroquiImportacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Arquivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdAplicacaoCroqui")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAplicacaoCroqui");

                    b.ToTable("AplicacaoCroquiImportacao");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aplicacao.AplicacaoLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdAplicacao")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdAplicacao");

                    b.ToTable("AplicacaoLog");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aplicacao.AplicacaoRecomendacoesTecnicas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlturaVooCustom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Angulo")
                        .HasColumnType("int");

                    b.Property<int?>("IdAeronave")
                        .HasColumnType("int");

                    b.Property<int?>("IdAlturaVoo")
                        .HasColumnType("int");

                    b.Property<int?>("IdAplicacao")
                        .HasColumnType("int");

                    b.Property<int?>("IdEquipamento")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoDeProduto")
                        .HasColumnType("int");

                    b.Property<int?>("IdVeiculante")
                        .HasColumnType("int");

                    b.Property<int?>("LarguraFaixa")
                        .HasColumnType("int");

                    b.Property<int?>("QtdeVeiculante")
                        .HasColumnType("int");

                    b.Property<int?>("Temperatura")
                        .HasColumnType("int");

                    b.Property<int?>("UrDoAR")
                        .HasColumnType("int");

                    b.Property<int?>("VelocidadeVento")
                        .HasColumnType("int");

                    b.Property<int?>("VolumeAplicacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAeronave");

                    b.HasIndex("IdAlturaVoo");

                    b.HasIndex("IdAplicacao");

                    b.HasIndex("IdEquipamento");

                    b.HasIndex("IdTipoDeProduto");

                    b.HasIndex("IdVeiculante");

                    b.ToTable("AplicacaoRecomendacoesTecnicas");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aplicacao.AplicacaoRelatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alteracoes_Observacoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Dosagem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("IdAplicacao")
                        .HasColumnType("int");

                    b.Property<int?>("IdPista")
                        .HasColumnType("int");

                    b.Property<string>("KG_LT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalAreaAplicada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VolumeAplicacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAplicacao");

                    b.HasIndex("IdPista");

                    b.ToTable("AplicacaoRelatorio");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aplicacao.AplicacaoRelatorioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HoraInicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraTermino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorimetroInicial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorimetroTermino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdAplicacaoRelatorio")
                        .HasColumnType("int");

                    b.Property<string>("ImagemDadosClimaticos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemperaturaFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemperaturaInicial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrInicial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VentoFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VentoInicial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdAplicacaoRelatorio");

                    b.ToTable("AplicacaoRelatorioItem");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Cidades.Cidades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Cliente.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdTipoCliente")
                        .HasColumnType("int");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precificacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UF")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.CombateIncendio.CombateIncendio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aviso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComandanteOcorrenciaAssinatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComandanteOcorrenciaNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComandanteOcorrenciaPosto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComandanteOcorrenciaRE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordenadorBaseOperacionalAssinatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordenadorBaseOperacionalNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordenadorBaseOperacionalPosto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordenadorBaseOperacionalRE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraInicial")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HorarioFinalOperacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("HorimetroAviao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorimetroFinalOperacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdAeronave")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdExecutor")
                        .HasColumnType("int");

                    b.Property<int?>("IdPista")
                        .HasColumnType("int");

                    b.Property<string>("LocalIncendioLat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalIncendioLon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OrgaoPublico_Privado")
                        .HasColumnType("bit");

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsavelOcorrenciaAssinatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsavelOcorrenciaNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsavelOcorrenciaPosto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsavelOcorrenciaRE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalAguaUtilizadaOperacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAeronave");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdExecutor");

                    b.HasIndex("IdPista");

                    b.ToTable("CombateIncendio");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.CombateIncendio.CombateIncendioDecolagemPouso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DecolagemHorario")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecolagemHorimetro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCombateIncendio")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PousoHorario")
                        .HasColumnType("datetime2");

                    b.Property<string>("PousoHorimetro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCombateIncendio");

                    b.ToTable("CombateIncendioDecolagemPouso");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Combustivel.Combustivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Combustivel");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Componentes.Componentes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EnumTBO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnumTLV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdAeronave")
                        .HasColumnType("int");

                    b.Property<string>("NomeComponente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrazoParaInspecao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TBO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TLV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TSN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TSO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UltimaInspecao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdAeronave");

                    b.ToTable("Componente");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Controle_De_Frota.ControleDeFrota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Combustivel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HorimetroFinal")
                        .HasColumnType("int");

                    b.Property<int?>("HorimetroInicial")
                        .HasColumnType("int");

                    b.Property<int?>("IdAeronave")
                        .HasColumnType("int");

                    b.Property<int?>("IdFrota")
                        .HasColumnType("int");

                    b.Property<int?>("IdPiloto")
                        .HasColumnType("int");

                    b.Property<int?>("KmFinal")
                        .HasColumnType("int");

                    b.Property<int?>("KmInicial")
                        .HasColumnType("int");

                    b.Property<int?>("LocalInicial")
                        .HasColumnType("int");

                    b.Property<string>("LocalizacaoPistaLat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalizacaoPistaLon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QtdeCombustivel")
                        .HasColumnType("int");

                    b.Property<int?>("QtdeHectare")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAeronave");

                    b.HasIndex("IdFrota");

                    b.HasIndex("IdPiloto");

                    b.ToTable("ControleDeFrota");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Cultura.Cultura", b =>
                {
                    b.Property<int>("IdCultura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCultura"));

                    b.Property<string>("AlvoBiologico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCultura");

                    b.ToTable("Cultura");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Empresa.Bula", b =>
                {
                    b.Property<int>("IdBula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBula"));

                    b.Property<string>("Adjuvante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoseProdutoComercial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdAlvoBiologico")
                        .HasColumnType("int");

                    b.Property<int?>("IdClassificacaoToxicologica")
                        .HasColumnType("int");

                    b.Property<int?>("IdCultura")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoDeServico")
                        .HasColumnType("int");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Removido")
                        .HasColumnType("bit");

                    b.Property<string>("TipoDeFormulacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBula");

                    b.HasIndex("IdAlvoBiologico");

                    b.HasIndex("IdCultura");

                    b.ToTable("Bula");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Empresa.BulaAplicacao", b =>
                {
                    b.Property<int>("IdBulaAplicacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBulaAplicacao"));

                    b.Property<string>("DoseProdutoComercial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdAlvoBiologico")
                        .HasColumnType("int");

                    b.Property<int?>("IdBula")
                        .HasColumnType("int");

                    b.Property<int?>("IdCultura")
                        .HasColumnType("int");

                    b.Property<int?>("TipoDeUnidade")
                        .HasColumnType("int");

                    b.HasKey("IdBulaAplicacao");

                    b.HasIndex("IdAlvoBiologico");

                    b.HasIndex("IdBula");

                    b.HasIndex("IdCultura");

                    b.ToTable("BulaAplicacao");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Empresa.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Imagem")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NrCDA")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistroMapa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmpresa");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Empresa.PlanoDeContrato", b =>
                {
                    b.Property<int>("IdPlano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlano"));

                    b.Property<string>("NomeDoPlano")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPlano");

                    b.ToTable("PlanoDeContrato");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Engenheiro.Engenheiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assinatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PorcentagemComissao")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Engenheiro");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Equipamento.Equipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipamento");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Estados.Estados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Executor.Executor", b =>
                {
                    b.Property<int>("IdExecutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExecutor"));

                    b.Property<byte[]>("Assinatura")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CFTA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdExecutor");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Executor");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Frota.Frota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Combustivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hodometro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("NomeVeiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Frota");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.ManutencaoAeronave.ManutencaoAeronave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Documento")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("HorasInspecao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorasRevisao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorimetroInicial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdAeronave")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAeronave");

                    b.ToTable("ManutencaoAeronave");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Menu.Menu", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuItemId");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.MenuUsuario.MenuUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdSubMenu")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdSubMenu");

                    b.HasIndex("IdUsuario");

                    b.ToTable("MenuUsuario");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Piloto.Piloto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assinatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CANAC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PorcentagemComissao")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Piloto");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Pistas.Pista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LAT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LONG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pista");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Precificacao.Precificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DistanciaPista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecoHA")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Precificacao");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Produto.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassificacaoToxicologica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCultura")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDeFormulacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoServico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCultura");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.SubMenu.SubMenu", b =>
                {
                    b.Property<int>("SubMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubMenuId"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubMenuId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("SubMenu");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Tipo_Produto.TipoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoProduto");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Veiculante.Veiculante", b =>
                {
                    b.Property<int>("IdVeiculante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVeiculante"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVeiculante");

                    b.ToTable("Veiculante");
                });

            modelBuilder.Entity("Domain.Entidades.User.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Credencial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Funcao")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NrUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("PrimeiroAcesso")
                        .HasColumnType("bit");

                    b.Property<bool>("Removido")
                        .HasColumnType("bit");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Alvo_Biologico.AlvoBiologico", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Produto.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aplicacao.Aplicacao", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Cliente.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente");

                    b.HasOne("Domain.Entidades.Cadastros.Cultura.Cultura", "Cultura")
                        .WithMany()
                        .HasForeignKey("IdCultura");

                    b.HasOne("Domain.Entidades.Cadastros.Empresa.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa");

                    b.HasOne("Domain.Entidades.Cadastros.Executor.Executor", "Executor")
                        .WithMany()
                        .HasForeignKey("IdExecutor");

                    b.HasOne("Domain.Entidades.Cadastros.Piloto.Piloto", "Piloto")
                        .WithMany()
                        .HasForeignKey("IdPiloto");

                    b.Navigation("Cliente");

                    b.Navigation("Cultura");

                    b.Navigation("Empresa");

                    b.Navigation("Executor");

                    b.Navigation("Piloto");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aplicacao.AplicacaoAreaTratada", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Aplicacao.Aplicacao", "Aplicacao")
                        .WithMany()
                        .HasForeignKey("IdAplicacao");

                    b.HasOne("Domain.Entidades.Cadastros.Cidades.Cidades", "Cidade")
                        .WithMany()
                        .HasForeignKey("IdCidade");

                    b.HasOne("Domain.Entidades.Cadastros.Estados.Estados", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado");

                    b.Navigation("Aplicacao");

                    b.Navigation("Cidade");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aplicacao.AplicacaoCaracteristicas", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Adjuvante.Adjuvante", "Adjuvante")
                        .WithMany()
                        .HasForeignKey("IdAdjuvante");

                    b.HasOne("Domain.Entidades.Cadastros.Aplicacao.Aplicacao", "Aplicacao")
                        .WithMany()
                        .HasForeignKey("IdAplicacao");

                    b.HasOne("Domain.Entidades.Cadastros.Produto.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto");

                    b.Navigation("Adjuvante");

                    b.Navigation("Aplicacao");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aplicacao.AplicacaoContrato", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Aplicacao.Aplicacao", "Aplicacao")
                        .WithMany()
                        .HasForeignKey("IdAplicacao");

                    b.HasOne("Domain.Entidades.Cadastros.Cidades.Cidades", "Cidade")
                        .WithMany()
                        .HasForeignKey("IdCidade");

                    b.HasOne("Domain.Entidades.Cadastros.Estados.Estados", "Estado")
                        .WithMany()
                        .HasForeignKey("IdUF");

                    b.Navigation("Aplicacao");

                    b.Navigation("Cidade");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aplicacao.AplicacaoCroqui", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Aplicacao.Aplicacao", "Aplicacao")
                        .WithMany()
                        .HasForeignKey("IdAplicacao");

                    b.Navigation("Aplicacao");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aplicacao.AplicacaoCroquiImportacao", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Aplicacao.AplicacaoCroqui", "AplicacaoCroqui")
                        .WithMany()
                        .HasForeignKey("IdAplicacaoCroqui");

                    b.Navigation("AplicacaoCroqui");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aplicacao.AplicacaoLog", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Aplicacao.Aplicacao", "Aplicacao")
                        .WithMany()
                        .HasForeignKey("IdAplicacao");

                    b.Navigation("Aplicacao");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aplicacao.AplicacaoRecomendacoesTecnicas", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Aeronave.Aeronave", "Aeronave")
                        .WithMany()
                        .HasForeignKey("IdAeronave");

                    b.HasOne("Domain.Entidades.Cadastros.Altura_Voo.AlturaVoo", "AlturaVoo")
                        .WithMany()
                        .HasForeignKey("IdAlturaVoo");

                    b.HasOne("Domain.Entidades.Cadastros.Aplicacao.Aplicacao", "Aplicacao")
                        .WithMany()
                        .HasForeignKey("IdAplicacao");

                    b.HasOne("Domain.Entidades.Cadastros.Equipamento.Equipamento", "Equipamento")
                        .WithMany()
                        .HasForeignKey("IdEquipamento");

                    b.HasOne("Domain.Entidades.Cadastros.Tipo_Produto.TipoProduto", "TipoProduto")
                        .WithMany()
                        .HasForeignKey("IdTipoDeProduto");

                    b.HasOne("Domain.Entidades.Cadastros.Veiculante.Veiculante", "Veiculante")
                        .WithMany()
                        .HasForeignKey("IdVeiculante");

                    b.Navigation("Aeronave");

                    b.Navigation("AlturaVoo");

                    b.Navigation("Aplicacao");

                    b.Navigation("Equipamento");

                    b.Navigation("TipoProduto");

                    b.Navigation("Veiculante");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aplicacao.AplicacaoRelatorio", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Aplicacao.Aplicacao", "Aplicacao")
                        .WithMany()
                        .HasForeignKey("IdAplicacao");

                    b.HasOne("Domain.Entidades.Cadastros.Pistas.Pista", "Pista")
                        .WithMany()
                        .HasForeignKey("IdPista");

                    b.Navigation("Aplicacao");

                    b.Navigation("Pista");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Aplicacao.AplicacaoRelatorioItem", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Aplicacao.AplicacaoRelatorio", "AplicacaoRelatorio")
                        .WithMany()
                        .HasForeignKey("IdAplicacaoRelatorio");

                    b.Navigation("AplicacaoRelatorio");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.CombateIncendio.CombateIncendio", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Aeronave.Aeronave", "Aeronave")
                        .WithMany()
                        .HasForeignKey("IdAeronave");

                    b.HasOne("Domain.Entidades.Cadastros.Empresa.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa");

                    b.HasOne("Domain.Entidades.Cadastros.Executor.Executor", "Executor")
                        .WithMany()
                        .HasForeignKey("IdExecutor");

                    b.HasOne("Domain.Entidades.Cadastros.Pistas.Pista", "Pista")
                        .WithMany()
                        .HasForeignKey("IdPista");

                    b.Navigation("Aeronave");

                    b.Navigation("Empresa");

                    b.Navigation("Executor");

                    b.Navigation("Pista");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.CombateIncendio.CombateIncendioDecolagemPouso", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.CombateIncendio.CombateIncendio", "CombateIncendio")
                        .WithMany()
                        .HasForeignKey("IdCombateIncendio");

                    b.Navigation("CombateIncendio");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Componentes.Componentes", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Aeronave.Aeronave", "Aeronave")
                        .WithMany()
                        .HasForeignKey("IdAeronave");

                    b.Navigation("Aeronave");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Controle_De_Frota.ControleDeFrota", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Aeronave.Aeronave", "Aeronave")
                        .WithMany()
                        .HasForeignKey("IdAeronave");

                    b.HasOne("Domain.Entidades.Cadastros.Frota.Frota", "Frota")
                        .WithMany()
                        .HasForeignKey("IdFrota");

                    b.HasOne("Domain.Entidades.Cadastros.Piloto.Piloto", "Piloto")
                        .WithMany()
                        .HasForeignKey("IdPiloto");

                    b.Navigation("Aeronave");

                    b.Navigation("Frota");

                    b.Navigation("Piloto");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Empresa.Bula", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Alvo_Biologico.AlvoBiologico", "AlvoBiologico")
                        .WithMany()
                        .HasForeignKey("IdAlvoBiologico");

                    b.HasOne("Domain.Entidades.Cadastros.Cultura.Cultura", "Cultura")
                        .WithMany()
                        .HasForeignKey("IdCultura");

                    b.Navigation("AlvoBiologico");

                    b.Navigation("Cultura");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Empresa.BulaAplicacao", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Alvo_Biologico.AlvoBiologico", "AlvoBiologico")
                        .WithMany()
                        .HasForeignKey("IdAlvoBiologico");

                    b.HasOne("Domain.Entidades.Cadastros.Empresa.Bula", "Bula")
                        .WithMany()
                        .HasForeignKey("IdBula");

                    b.HasOne("Domain.Entidades.Cadastros.Cultura.Cultura", "Cultura")
                        .WithMany()
                        .HasForeignKey("IdCultura");

                    b.Navigation("AlvoBiologico");

                    b.Navigation("Bula");

                    b.Navigation("Cultura");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Engenheiro.Engenheiro", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Empresa.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Executor.Executor", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Empresa.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Frota.Frota", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Empresa.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.ManutencaoAeronave.ManutencaoAeronave", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Aeronave.Aeronave", "Aeronave")
                        .WithMany()
                        .HasForeignKey("IdAeronave");

                    b.Navigation("Aeronave");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.MenuUsuario.MenuUsuario", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.SubMenu.SubMenu", "SubMenu")
                        .WithMany()
                        .HasForeignKey("IdSubMenu");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubMenu");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Precificacao.Precificacao", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Empresa.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.Produto.Produto", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Cultura.Cultura", "Cultura")
                        .WithMany()
                        .HasForeignKey("IdCultura");

                    b.Navigation("Cultura");
                });

            modelBuilder.Entity("Domain.Entidades.Cadastros.SubMenu.SubMenu", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Menu.Menu", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("Domain.Entidades.User.Usuario", b =>
                {
                    b.HasOne("Domain.Entidades.Cadastros.Empresa.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
